test: Add composeTestRule.waitForIdle() in PoetAssistantComposeTestRule.
This is an attempt to avoid this error:

java.lang.RuntimeException: java.util.concurrent.ExecutionException: androidx.test.espresso.IdlingResourceTimeoutException: Wait for [Compose-Espresso link] to become idle timed out
at androidx.test.espresso.Espresso.onIdle(Espresso.java:357)
at androidx.test.espresso.Espresso.onIdle(Espresso.java:378)
at ca.rmen.android.poetassistant.main.rules.ActivityTestRules.cleanup(ActivityTestRules.kt:86)
at ca.rmen.android.poetassistant.main.rules.ActivityTestRules.beforeActivityLaunched(ActivityTestRules.kt:57)
at ca.rmen.android.poetassistant.rules.PoetAssistantComposeTestRule.finished(PoetAssistantComposeTestRule.kt:39)

Also make its finished() method call ActivityTestRules.afterActivityFinished() instead of ActivityTestRules.beforeActivityLaunched(). Not sure why it was calling the before method before.