fix: Fix crash in instrumentation tests when changing the theme.
Doc: https://developer.android.com/topic/libraries/architecture/views/coroutines-views

Also add a lifecycle state check (probably only relevant to tests) to prevent this crash.

java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner for
  ResultListHeaderFragment{58f195b} (a83bb21f-051c-4b04-8487-f36bcba7d19f) when getView() is null i.e., before onCreateView() or after onDestroyView()
  at androidx.fragment.app.Fragment.getViewLifecycleOwner(Fragment.java:390)
  at ca.rmen.android.poetassistant.main.dictionaries.ResultListHeaderFragment$onCreateView$3$2.invokeSuspend(ResultListHeaderFragment.kt:84)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
  at ca.rmen.android.poetassistant.testsupport.CountingIdlingResourceDispatcher.dispatch$lambda$0(CountingIdlingResourceDispatcher.kt:20)
  at ca.rmen.android.poetassistant.testsupport.CountingIdlingResourceDispatcher$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
  at android.os.Handler.handleCallback(Handler.java:958)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at androidx.test.espresso.base.TestLooperManagerCompat.execute(TestLooperManagerCompat.java:121)
  at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:128)
  at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:513)
  at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:469)
  at androidx.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:235)
  at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:175)
  at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:138)
  at androidx.test.espresso.action.Tap.sendSingleTap(Tap.java:168)
  at androidx.test.espresso.action.Tap.-$$Nest$smsendSingleTap(Unknown Source:0)
  at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:46)