Only enable jacoco if we're running tests
Fix this crash:
```
Process: ca.rmen.android.poetassistant.test, PID: 4738
java.lang.RuntimeException: Unable to instantiate application ca.rmen.android.poetassistant.PoetAssistantApplication: java.lang.RuntimeException: Failed to initialize JaCoCo.
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1244)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6683)
	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.RuntimeException: Failed to initialize JaCoCo.
	at org.jacoco.agent.rt.internal_f3994fa.Offline.getRuntimeData(Offline.java:41)
	at org.jacoco.agent.rt.internal_f3994fa.Offline.getProbes(Offline.java:60)
	at ca.rmen.android.poetassistant.PoetAssistantApplication.$jacocoInit(Unknown Source:12)
	at ca.rmen.android.poetassistant.PoetAssistantApplication.<init>(Unknown Source:0)
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
	at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1158)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1236)
	... 9 more
Caused by: java.io.FileNotFoundException: /jacoco.exec: open failed: EROFS (Read-only file system)
	at libcore.io.IoBridge.open(IoBridge.java:492)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
	at org.jacoco.agent.rt.internal_f3994fa.output.FileOutput.openFile(FileOutput.java:68)
	at org.jacoco.agent.rt.internal_f3994fa.output.FileOutput.startup(FileOutput.java:50)
	at org.jacoco.agent.rt.internal_f3994fa.Agent.startup(Agent.java:129)
	at org.jacoco.agent.rt.internal_f3994fa.Agent.getInstance(Agent.java:54)
	at org.jacoco.agent.rt.internal_f3994fa.Offline.getRuntimeData(Offline.java:39)
	... 17 more
Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7542)
	at libcore.io.IoBridge.open(IoBridge.java:478)
	... 23 more
```