Remove retainInstance for ReaderFragment.
This was causing a crash when the theme changed, since introducing hilt:

 java.lang.RuntimeException: Unable to start activity ComponentInfo{ca.rmen.android.poetassistant.test/ca.rmen.android.poetassistant.main.MainActivity}: java.lang.IllegalStateException: onAttach called multiple times with different Context! Hilt Fragments should not be retained.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4048)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4235)
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6304)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6195)
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:79)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
        at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174)
        at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
        at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:68)
        at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:6261)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2649)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loopOnce(Looper.java:232)
        at android.os.Looper.loop(Looper.java:317)
        at android.app.ActivityThread.main(ActivityThread.java:8705)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
 Caused by: java.lang.IllegalStateException: onAttach called multiple times with different Context! Hilt Fragments should not be retained.
        at dagger.hilt.internal.Preconditions.checkState(Preconditions.java:83)
        at ca.rmen.android.poetassistant.main.reader.Hilt_ReaderFragment.onAttach(Hilt_ReaderFragment.java:58)
        at androidx.fragment.app.Fragment.onAttach(Fragment.java:1888)
        at ca.rmen.android.poetassistant.main.reader.Hilt_ReaderFragment.onAttach(Hilt_ReaderFragment.java:47)
        at androidx.fragment.app.Fragment.performAttach(Fragment.java:3075)
        at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:510)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:279)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1685)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3319)
        at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:3226)
        at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:252)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:219)
        at ca.rmen.android.poetassistant.main.Hilt_MainActivity.onCreate(Hilt_MainActivity.java:62)
        at ca.rmen.android.poetassistant.main.MainActivity.onCreate(MainActivity.kt:89)