Fix bug on Android 14 with WOTD notification
Use the `FLAG_IMMUTABLE` flag, instead of `FLAG_MUTABLE`:

```
java.lang.IllegalArgumentException: ca.rmen.android.poetassistant.test: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
```